name: rust

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  FOUNDRY_PROFILE: ci

jobs:
  build_clippy:
    name: build+clippy
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            *.rs
            *.toml
            *.lock

      - uses: dtolnay/rust-toolchain@1.79.0
        with:
          components: clippy

      - uses: taiki-e/install-action@cargo-binstall

      - name: Install risc0 tooling
        shell: bash
        run: |
          cargo binstall cargo-risczero -y
          cargo risczero install
          cargo risczero --version

      - run: cargo build
        if: env.GIT_DIFF

      - run:  cargo clippy
        if: env.GIT_DIFF
        env:
          RISC0_SKIP_BUILD: true
          RUSTFLAGS: "-D warnings"

  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            *.rs
            *.toml
            *.lock

      - uses: dtolnay/rust-toolchain@1.79.0

      - uses: taiki-e/install-action@cargo-binstall

      - name: Install risc0 tooling
        shell: bash
        run: |
          cargo binstall cargo-risczero -y
          cargo risczero install
          cargo risczero --version

      - run: cargo test
        if: env.GIT_DIFF

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            *.rs
            *.toml
            *.lock

      - uses: dtolnay/rust-toolchain@nightly
        if: env.GIT_DIFF
        with:
          components: rustfmt

      - run: cargo +nightly fmt --all --check
        if: env.GIT_DIFF

  docs:
    name: docs
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            *.rs
            *.toml
            *.lock

      - name: common setup
        if: env.GIT_DIFF
        uses: ./.github/actions/setup

      - run: cargo doc --document-private-items --no-deps
        if: env.GIT_DIFF
        env: 
          RUSTDOCFLAGS: "--cfg docsrs -D warnings"