[package]
name = "app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "clob"
path = "src/clob.rs"

[workspace]

[dependencies]
risc0-zkvm = { version = "1", default-features = false, features = ['std'] }
borsh = { version = "1", default-features = false }

clob-core = { path = "../../core" }

