[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
risc0-build = { workspace = true }
zkvm-utils = { path = "../zkvm-utils" }

[package.metadata.risc0]
methods = ["app"]
