name: contracts
on:
  push:
    branches:
      - main
    paths:
      - "contracts/**"
      - ".github/**"
  pull_request:
    paths:
      - "contracts/**"
      - ".github/**"
  workflow_dispatch:

permissions:
  contents: read

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@1.80

      - uses: taiki-e/install-action@cargo-binstall

      - name: Install sp1 tooling
        shell: bash
        run: |
          curl -L https://sp1.succinct.xyz | bash
          echo "$HOME/.sp1/bin" >> $GITHUB_PATH
      - name: Check sp1 version
        shell: bash
        run: |
          sp1up
          cargo prove --version

      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: build rust workspace
        run: cargo build
        working-directory: .

      - name: build
        run: |
          forge --version
          forge build --sizes

      - name: test
        run: |
          forge test -vvv --ffi
