name: rust

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths
on:
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - "**.lock"
      - "**.toml"
      - ".github/**"
  pull_request:
    paths:
      - "**.rs"
      - "**.lock"
      - "**.toml"
      - ".github/**"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  FOUNDRY_PROFILE: ci

jobs:
  build_clippy:
    name: build+clippy
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@1.80
        with:
          components: clippy

      - uses: taiki-e/install-action@cargo-binstall

      - name: Install sp1 tooling
        shell: bash
        run: |
          curl -L https://sp1.succinct.xyz | bash
          echo "$HOME/.sp1/bin" >> $GITHUB_PATH
      - name: Check sp1 version
        shell: bash
        run: |
          sp1up
          cargo prove --version

      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: run cargo build
        run: cargo build

      - name: run cargo clippy
        run: cargo clippy
        env:
          RUSTFLAGS: "-D warnings"

  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@1.80

      - uses: taiki-e/install-action@cargo-binstall

      - name: Install sp1 tooling
        shell: bash
        run: |
          curl -L https://sp1.succinct.xyz | bash
          echo "$HOME/.sp1/bin" >> $GITHUB_PATH
      - name: Check sp1 version
        shell: bash
        run: |
          sp1up
          cargo prove --version

      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: cargo test

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: run cargo fmt
        run: cargo +nightly fmt --all --check

  unused-deps:
    name: unused deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@nightly

      - name: install cargo-machete
        run: cargo install cargo-machete

      - name: run cargo-machete
        run: cargo machete
